"""
Market Symbol Universe
Defines the expanded list of assets for the terminal.
Includes:
- Major Global & Domestic Indices
- Sectoral & Thematic Indices (NSE)
- NIFTY 50 (Top 50)
- NIFTY NEXT 50
- Key Midcap 100 Selections
"""

# Major Indices
INDICES = {
    # Benchmark
    "NIFTY 50": "^NSEI",
    "SENSEX": "^BSESN",
    "NIFTY BANK": "^NSEBANK",
    "FINNIFTY": "NIFTY_FIN_SERVICE.NS",
    "NIFTY MIDCAP 100": "NIFTY_MIDCAP_100.NS",
    "NIFTY NEXT 50": "^NSMIDCP", # Ticker can vary, often ^NSMIDCP or similar on Yahoo
    "INDIA VIX": "^INDIAVIX",

    # Sectoral Indices (Yahoo Finance Tickers)
    "NIFTY AUTO": "^CNXAUTO",
    "NIFTY IT": "^CNXIT",
    "NIFTY PHARMA": "^CNXPHARMA",
    "NIFTY FMCG": "^CNXFMCG",
    "NIFTY METAL": "^CNXMETAL",
    "NIFTY REALTY": "^CNXREALTY",
    "NIFTY ENERGY": "^CNXENERGY",
    "NIFTY MEDIA": "^CNXMEDIA",
    "NIFTY INFRA": "^CNXINFRA",
    "NIFTY PSU BANK": "^CNXPSUBANK",
    "NIFTY PVT BANK": "NIFTY_PVT_BANK.NS", # Sometimes varies
    "NIFTY COMMODITIES": "^CNXCMDT",
    "NIFTY CONSUMPTION": "^CNXCONSUM",
    "NIFTY CPSE": "^CNXPSE", # CPSE Index
    "NIFTY PSE": "^CNXPSE", 
    "NIFTY MNC": "^CNXMNC",
    "NIFTY SERVICE": "^CNXSERVICE",

    # Global
    "S&P 500 (US)": "^GSPC",
    "NASDAQ (US)": "^IXIC",
    "DOW JONES (US)": "^DJI",
    "DAX (Germany)": "^GDAXI",
    "FTSE 100 (UK)": "^FTSE",
    "NIKKEI 225 (Japan)": "^N225"
}

# Commodities & Forex
MACRO_ASSETS = {
    "GOLD Futures": "GC=F",
    "SILVER Futures": "SI=F",
    "CRUDE OIL (WTI)": "CL=F",
    "BRENT OIL": "BZ=F",
    "COPPER": "HG=F",
    "NATURAL GAS": "NG=F",
    "USD/INR": "INR=X",
    "EUR/INR": "EURINR=X",
    "GBP/INR": "GBPINR=X",
    "JPY/INR": "JPYINR=X",
    "DOLLAR INDEX": "DX-Y.NYB",
    "US 10Y YIELD": "^TNX"
}

# Top 200 Indian Stocks (Nifty 50 + Next 50 + Midcaps)
# Suffix '.NS' is required for Yahoo Finance
STOCKS = [
    # --- NIFTY 50 ---
    "RELIANCE.NS", "TCS.NS", "HDFCBANK.NS", "ICICIBANK.NS", "INFY.NS", "BHARTIARTL.NS", "ITC.NS", "SBIN.NS",
    "LICI.NS", "HINDUNILVR.NS", "KOTAKBANK.NS", "LT.NS", "AXISBANK.NS", "HCLTECH.NS", "BAJFINANCE.NS",
    "MARUTI.NS", "ASIANPAINT.NS", "SUNPHARMA.NS", "TITAN.NS", "ULTRACEMCO.NS", "TATASTEEL.NS", "NTPC.NS",
    "M&M.NS", "POWERGRID.NS", "TATAMOTORS.NS", "ADANIENT.NS", "BAJAJFINSV.NS", "COALINDIA.NS", "ONGC.NS",
    "NESTLEIND.NS", "JSWSTEEL.NS", "GRASIM.NS", "TECHM.NS", "ADANIPORTS.NS", "HINDALCO.NS", "CIPLA.NS",
    "WIPRO.NS", "SBILIFE.NS", "DRREDDY.NS", "EICHERMOT.NS", "HDFCLIFE.NS", "BPCL.NS", "DIVISLAB.NS",
    "TATACONSUM.NS", "APOLLOHOSP.NS", "BAJAJ-AUTO.NS", "BRITANNIA.NS", "HEROMOTOCO.NS", "INDUSINDBK.NS", "UPL.NS",

    # --- NIFTY NEXT 50 & MIDCAPS ---
    "ADANIENSOL.NS", "ADANIGREEN.NS", "ADANIPOWER.NS", "ATGL.NS", "AMBUJACEM.NS", "AWL.NS", "ABCAPITAL.NS",
    "ABFRL.NS", "ACC.NS", "ALKEM.NS", "AUROPHARMA.NS", "BAJAJHLDNG.NS", "BANDHANBNK.NS", "BANKBARODA.NS",
    "BEL.NS", "BERGEPAINT.NS", "BIOCON.NS", "BOSCHLTD.NS", "CANBK.NS", "CHOLAFIN.NS", "COLPAL.NS", "DLF.NS",
    "DABUR.NS", "GAIL.NS", "GODREJCP.NS", "GODREJPROP.NS", "HAVELLS.NS", "HAL.NS", "ICICIGI.NS", "ICICIPRULI.NS",
    "IOC.NS", "IRCTC.NS", "IGL.NS", "INDUSTOWER.NS", "JINDALSTEL.NS", "LTIM.NS", "MARICO.NS", "MPHASIS.NS",
    "MUTHOOTFIN.NS", "NAUKRI.NS", "NYKAA.NS", "PAYTM.NS", "PAGEIND.NS", "PERSISTENT.NS", "PIDILITIND.NS",
    "PIIND.NS", "PNB.NS", "PFC.NS", "PGHH.NS", "RECLTD.NS", "SBICARD.NS", "SRF.NS", "SHREECEM.NS", "SIEMENS.NS",
    "SRTRANSFIN.NS", "TATACHEM.NS", "TATAELXSI.NS", "TATAPOWER.NS", "TORNTPHARM.NS", "TRENT.NS", "TVSMOTOR.NS",
    "UNITEDSPIR.NS", "VBL.NS", "VEDL.NS", "ZOMATO.NS", "ZYDUSLIFE.NS",
    
    # --- ADDITIONAL LIQUID MIDCAPS ---
    "ASHOKLEY.NS", "AUBANK.NS", "BALKRISIND.NS", "BATAINDIA.NS", "BHARATFORG.NS", "CANFINHOME.NS", "CONCOR.NS",
    "CUMMINSIND.NS", "DEEPAKNTR.NS", "ESCORTS.NS", "EXIDEIND.NS", "FEDERALBNK.NS", "GMRINFRA.NS", "GNFC.NS",
    "GUJGASLTD.NS", "IDFCFIRSTB.NS", "IPCALAB.NS", "JSL.NS", "JUBLFOOD.NS", "LALPATHLAB.NS", "LAURUSLAB.NS",
    "LICHSGFIN.NS", "LUPIN.NS", "MANAPPURAM.NS", "MFSL.NS", "MGL.NS", "MINDTREE.NS", "NAM-INDIA.NS",
    "OBEROIRLTY.NS", "POLYCAB.NS", "RBLBANK.NS", "RAMCOCEM.NS", "SUNTV.NS", "SYNGENE.NS", "TATACOMM.NS",
    "TORNTPOWER.NS", "VOLTAS.NS", "WHIRLPOOL.NS", "ZEEL.NS", "DLF.NS", "GODREJPROP.NS", "PHOENIXLTD.NS"
]

# Sector Mapping for Drill-Down Analysis
SECTOR_CONSTITUENTS = {
    "NIFTY BANK": ["HDFCBANK.NS", "ICICIBANK.NS", "SBIN.NS", "KOTAKBANK.NS", "AXISBANK.NS", "INDUSINDBK.NS", "BANKBARODA.NS", "PNB.NS", "AUBANK.NS", "IDFCFIRSTB.NS", "FEDERALBNK.NS", "BANDHANBNK.NS"],
    "NIFTY IT": ["TCS.NS", "INFY.NS", "HCLTECH.NS", "WIPRO.NS", "TECHM.NS", "LTIM.NS", "PERSISTENT.NS", "MPHASIS.NS", "TATAELXSI.NS", "COFORGE.NS"],
    "NIFTY AUTO": ["MARUTI.NS", "TATAMOTORS.NS", "M&M.NS", "BAJAJ-AUTO.NS", "EICHERMOT.NS", "HEROMOTOCO.NS", "TVSMOTOR.NS", "ASHOKLEY.NS", "BHARATFORG.NS", "BALKRISIND.NS"],
    "NIFTY PHARMA": ["SUNPHARMA.NS", "DRREDDY.NS", "CIPLA.NS", "DIVISLAB.NS", "APOLLOHOSP.NS", "TORNTPHARM.NS", "ZYDUSLIFE.NS", "LUPIN.NS", "AUROPHARMA.NS", "ALKEM.NS", "BIOCON.NS", "LAURUSLAB.NS"],
    "NIFTY FMCG": ["ITC.NS", "HINDUNILVR.NS", "NESTLEIND.NS", "BRITANNIA.NS", "TATACONSUM.NS", "GODREJCP.NS", "DABUR.NS", "VARUN.NS", "MARICO.NS", "COLPAL.NS", "VBL.NS", "UNITEDSPIR.NS"],
    "NIFTY METAL": ["TATASTEEL.NS", "HINDALCO.NS", "JSWSTEEL.NS", "ADANIENT.NS", "VEDL.NS", "JINDALSTEL.NS", "SAIL.NS", "NMDC.NS", "NATIONALUM.NS"],
    "NIFTY ENERGY": ["RELIANCE.NS", "NTPC.NS", "ONGC.NS", "POWERGRID.NS", "BPCL.NS", "IOC.NS", "GAIL.NS", "TATAPOWER.NS", "ADANIGREEN.NS", "ADANIPOWER.NS"],
    "NIFTY REALTY": ["DLF.NS", "GODREJPROP.NS", "OBEROIRLTY.NS", "PHOENIXLTD.NS", "PRESTIGE.NS", "BRIGADE.NS"],
    "NIFTY CONSUMPTION": ["ASIANPAINT.NS", "TITAN.NS", "HAVELLS.NS", "VOLTAS.NS", "PAGEIND.NS", "TRENT.NS", "PIDILITIND.NS", "BERGEPAINT.NS"],
    "NIFTY INFRA": ["LT.NS", "ULTRACEMCO.NS", "GRASIM.NS", "SIEMENS.NS", "ABB.NS", "HAL.NS", "BEL.NS", "INDIGO.NS", "CONCOR.NS", "GMRINFRA.NS"]
}

# Helper to get all symbols
def get_all_symbols():
    return list(INDICES.values()) + list(MACRO_ASSETS.values()) + STOCKS

def get_stock_dict():
    """Returns a dict {Symbol: Ticker} for selectboxes"""
    stock_dict = {s.replace('.NS', ''): s for s in STOCKS}
    return stock_dict
